### ISSUE TITLE
エンハンスドロードバランサへの対応予定はありますか？

### ISSUE THREAD

**Issue by MasaGon** [sacloud/terraform-provider-sakuracloud#1098]
アプライアンスのロードバランサーがDSR方式で使い勝手が悪いので、エンハンスドロードバランサーの利用を検討しているのですが、こちらのプロバイダーで対応予定はございますか？
https://manual.sakura.ad.jp/cloud/appliance/enhanced-lb/index.html

**Comment by yamamoto-febc** [comment]
エンハンスドロードバランサーは以下のリソース/データソースで利用可能です。

- リソース
  - [sakuracloud_proxylb](https://registry.terraform.io/providers/sacloud/sakuracloud/latest/docs/resources/proxylb) ([日本語ドキュメント](https://docs.usacloud.jp/terraform/r/proxylb/))
  - [sakuracloud_proxylb_acme](https://registry.terraform.io/providers/sacloud/sakuracloud/latest/docs/resources/proxylb_acme) ([日本語ドキュメント](https://docs.usacloud.jp/terraform/r/proxylb_acme/))
- データソース
  - [sakuracloud_proxylb](https://registry.terraform.io/providers/sacloud/sakuracloud/latest/docs/data-sources/proxylb) ([日本語ドキュメント](https://docs.usacloud.jp/terraform/d/proxylb/))

**Comment by MasaGon** [comment]
@yamamoto-febc あ、ホントだ！見落としておりましてた。ありがとうございます！
