### ISSUE TITLE
Linux i386版でsakuracloud_diskのsize指定時にエラーが発生

### ISSUE THREAD

**Issue by zembutsu** [sacloud/terraform-provider-sakuracloud#149]
いつもありがとうございます。件名の通りです。
現行バージョンの Linux-386.zip で、リソース名 `sakuracloud_disk` のパラメータ指定でご確認のお願いがあります。条件は、

- plan "hdd"
かつ
- size 指定

の場合に、 `terraform plan` は通過しますが、 `terraform apply` 時、次のエラーが発生します。

```
 Status:"400 Bad Request", ErrorCode:"bad_request", ErrorMessage:"不適切な要求です。パラメータの指定誤り、入力規則違反です。入 力内容をご確認ください。\nThe source size (20480 MB) must be one of 40960,61440,81920,102400,256000,512000,768000,1048576,2097152,4194304 for Plan 2"}
```

エラー末尾の `Plan 2` の所、サイズ指定が正しく反映されないように見受けられます。
なお SSD では発生しませんでした。他に確認点がありましたら、お知らせください。

**Comment by yamamoto-febc** [comment]
@zembutsu , ご報告ありがとうございます！！

## 現象と原因

エラーメッセージを見ると、入力値として  

- ディスクプランに"hdd"
- ディスクサイズに20GB(20480 MB)

を指定しているように見受けられます。

この場合、今回のエラーの原因は以下２点と思われます。

- 1: ゾーン/ディスクプランの組み合わせ上、指定できないディスクサイズを指定していること
- 2: 入力値の相関チェックの仕組みがないこと  
(ゾーン/ディスクプランの値に応じてディスクサイズの検証を行っていないこと) 

以下順に説明いたします。

## 原因の詳細

### 1: ゾーン/ディスクプランの組み合わせ上、指定できないディスクサイズを指定していること

ディスクのサイズは対象ゾーンとディスクプランの選択次第で入力可能な値が決まります。
入力可能な値: [さくらのクラウド 機能・仕様 - サーバー/ディスク](http://cloud.sakura.ad.jp/specification/server-disk/#server-disk-content02)

今回はHDD(標準プラン)で指定できない20GBというサイズを指定したことでエラーとなっています。

### 2: 入力値の相関チェックの仕組みがないこと  

現在のTerraform(本体)の実装上、入力値の相関チェックを行う仕組みがありません。
例えば、planに"hdd"を選んだ場合、ディスクサイズは40GB以上を指定する必要がありますが、  
これを`terraform plan`の段階で判定してエラーとする方法が(現在は)ありません。  

このため、`terraform plan`でのチェックをくぐり抜け、さくらのクラウドAPIを呼び出す段階でエラーとなっているのだと思います。

## ワークアラウンド

[さくらのクラウド 機能・仕様 - サーバー/ディスク](http://cloud.sakura.ad.jp/specification/server-disk/#server-disk-content02)を参照し、ゾーン/ディスクプランに応じて選択可能なディスクサイズを指定してください。

## 対応

現時点では相関チェックを行うのは困難なため、ドキュメントに注意書きを追記ことで対応します。

**Comment by zembutsu** [comment]
@yamamoto-febc ご丁寧にありがとうございます。.tf ファイルの中では次のように指定していました。

```
    plan = "hdd"
    size = "40"
```

40 や、60、100 と指定していても、ErrorMessage では最後に `2` と出ていることから、容量の指定がうまくできていないように得ています。

なお、試しているリージョンは `tk1a` `tk1v` でした。
同じ.tf ファイルを使い、amd64 の terraform では正常に作成できるのですが、 i386 版のみで発生する現象でした。

他にも確認する箇所がありましたら、教えていただけますでしょうか。お手数をおかけします。

**Comment by yamamoto-febc** [comment]
なるほど、勘違いをしていたようです。  
再現確認してみます。

**Comment by yamamoto-febc** [comment]
再現しました。別途PullRequestを作成して対応します。

**Comment by zembutsu** [comment]
お手数をおかけします 🙇

**Comment by yamamoto-febc** [comment]
後ほど対応版である`v0.10.3`をリリースします。  
もし何かおかしい点などありましたら再オープンしてください:bow:
