### ISSUE TITLE
Disk情報, IPアドレスが変更されない

### ISSUE THREAD

**Issue by Masatoshi-Kouda** [sacloud/terraform-provider-sakuracloud#179]
## 事象

さくらクラウドパブリックアーカイブ(ubuntu)を元にPackerでアーカイブ作成後、
Terraformで対象のアーカイブIDを指定し実行したところ、ディスクで定義した内容や
OS側ethのIPアドレスが変更されない状況が発生しました。

パブリックアーカイブ(ubuntu)を指定した場合は正常に変更される。

カスタマイズしたアーカイブからサーバ作成する場合、下記ドキュメントの`注2`に記載されている
ようにOSによっては変更できないのでしょうか？

https://sacloud.github.io/terraform-provider-sakuracloud/configuration/resources/disk/

対処方法あれば教えて頂ければ幸いでございます :bow:

### Terraform

- terraform v0.10.5
- terraform-provider-sakuracloud: v0.13.0

### Packer

- packer v1.1.0
- packer-builder-sakuracloud: v0.1.1

### さくらクラウド パブリックアーカイブ

- Ubuntu 16.04.2 LTS

### Packer

```
{
  "builders": [{
    "type": "sakuracloud",
    "zone": "is1b",
    "os_type": "ubuntu",
    "user_name": "ubuntu",
    "password": "password",
    "core" : 2,
    "memory_size": 4
  }],
  "provisioners":[
  {
    "type": "shell",
    "execute_command": "echo 'password' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
    "inline": [
      "apt-get update -y",
      "echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/ubuntu",
      "chmod 0440 /etc/sudoers.d/ubuntu"
    ]
  }]
}
```

### Terraform

`sakuracloud_disk`の`source_archive_id`は上記のPackerで払い出されたIDを指定

```
##################################
# Provider
##################################
# 対象ゾーンを指定
provider sakuracloud {
  zone = "is1b"
}

##################################
# SSH KEY
##################################
# 公開鍵(さくらのクラウド上で生成)
resource "sakuracloud_ssh_key_gen" "key" {
  name = "foobar"

  provisioner "local-exec" {
    command = "echo \"${self.private_key}\" > id_rsa; chmod 0600 id_rsa"
  }

  provisioner "local-exec" {
    when    = "destroy"
    command = "rm -f id_rsa"
  }
}

##################################
# Startup Script
##################################
resource "sakuracloud_note" "startup-script" {
  name = "startup-script"
  content = <<EOF
#!/bin/bash
echo "127.0.0.1    $(hostname)" >> /etc/hosts
EOF
}

##################################
# DISK
##################################
# サーバーの管理者パスワードの定義
variable "password" {
  default = "password"
}

# ディスク定義
resource "sakuracloud_disk" "disk01" {
  name              = "disk01"
  source_archive_id = "112901177228"
  ssh_key_ids       = ["${sakuracloud_ssh_key_gen.key.id}"]
  password          = "${var.password}"
  disable_pw_auth   = true
  note_ids          = ["${sakuracloud_note.startup-script.id}"]
  hostname          = "server01"
}

##################################
# SERVER
##################################
# サーバー定義
resource "sakuracloud_server" "server01" {
  name  = "server01"
  disks = ["${sakuracloud_disk.disk01.id}"]
}

##################################
# OUTPUT
##################################
# サーバへのSSH接続を表示するアウトプット定義
output "ssh_to_server" {
  value = "ssh -i id_rsa ubuntu@${sakuracloud_server.server01.ipaddress}"
}
```

**Comment by yamamoto-febc** [comment]
ご連絡ありがとうございます！！
こちら、再現確認しました。

原因はTerraform for さくらのクラウド側でのディスクの修正可否判定にあります。  
以下のようにディスクの修正可否の判定を行い、修正不可であれば処理を行わないようになっています。

### ディスク修正可否の判定

サーバ/ディスクの作成/更新時、以下のルールでディスクの修正が行えるか判定しています。

- `server.BundleInfo`がある場合は不可(Windows)
- ソースアーカイブ/ソースディスク共に設定されていない場合は不可(ブランクディスク)
- タグ(`os-linux` or `os-unix`)が設定されていたら可
- これらの判定をソースアーカイブ/ソースディスクが辿れなくなるまで再帰処理

今回はpackerで作成されたものであるため、
- ソースアーカイブ = 空
- ソースディスク = packerで一時的に作成したサーバのディスク
となり、ソースディスク情報が辿れず、修正不可と判定されてしまいます。

該当箇所のソース:  
https://github.com/sacloud/libsacloud/blob/49f63d464c6a9a1598dd5aac41d18b3e043f2a2b/api/disk.go#L236-L277

暫定対応として、以下のワークアラウンドにて回避可能です。  

## ワークアラウンド

packerで作成したアーカイブに`os-linux`または`os-unix`タグを付与してください。
packerでアーカイブ作成時に付与する場合は以下のようにJSON内で`archive_tags`を指定することで付与可能です。

```json
{
  "builders": [{
    "type": "sakuracloud",
    "zone": "is1b",
    "os_type": "ubuntu",
    "user_name": "ubuntu",
    "password": "password",
    "core" : 2,
    "memory_size": 4,
    "archive_tags": ["os-linux","@size-extendable"]
  }],
  "provisioners":[
  {
    "type": "shell",
    "execute_command": "echo 'password' | {{ .Vars }} sudo -E -S sh '{{ .Path }}'",
    "inline": [
      "apt-get update -y",
      "echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/ubuntu",
      "chmod 0440 /etc/sudoers.d/ubuntu"
    ]
  }]
}
```

## 根本対応

packer側にて、ディスクの修正が可能なアーカイブ/ディスクから作成された場合に、`os-linux` or `os-unix`タグを自動的に付与するようにします。

**Comment by Masatoshi-Kouda** [comment]
@yamamoto-febc 
ディスク修正可否の判定について詳細に解説頂きありがとうございます！

教えて頂きましたpackerアーカイブ作成時に`archive_tags`に`os-linux`を指定することで、
terraform側で設定したDISKの修正項目が正常に反映されることが確認できました！

大変助かりました、ありがとうございます！！

**Comment by yamamoto-febc** [comment]
@Masatoshi-Kouda ,

動作したようでよかったです！！
当Issueは [sacloud/packer-builder-sakuracloud#13](https://github.com/sacloud/packer-builder-sakuracloud/issues/13)の対応を行うまでOpenのままにしておきます。

Packer for さくらのクラウド側の対応が行われるまで`archive_tags`を利用する方法での回避をお願いいたします。

**Comment by yamamoto-febc** [comment]
Packer for さくらのクラウド側にて対応を行ったためクローズします。
