### ISSUE TITLE
設定ファイル中でタグをソートしていない場合、apply 後も差分が残る

### ISSUE THREAD

**Issue by hitsumabushi** [sacloud/terraform-provider-sakuracloud#234]
# 概要
さくらのクラウドのAPIではタグをソートせずに、POST/PUTした場合でも戻り値はソートされている。
このため、 設定ファイル中でタグをソートしていない場合 `terraform apply` しても、tfstate の状態と設定が異なることになり、何度 apply しても差分を解消することができない。

# ワークアラウンド
設定ファイル中のタグの記述をソートしておく。

**Comment by yamamoto-febc** [comment]
ありがとうございます！

現状ではどの順番でタグを登録してもAPI側ソートされてしまうため差分が発生してしまうことがあります。

近いうちに#213 とあわせ、Terraformの[CustomizeDiff](https://github.com/hashicorp/terraform/blob/v0.11.1/helper/schema/resource.go#L117)対応を行う予定ですのでこの時に解消できると思います。

それまではご提示いただいたワークアラウンドをお試しください。

**Comment by yamamoto-febc** [comment]
#237 にて対応しました。次のリリース時に含めますのでリリースまでしばしお待ちください。
