### ISSUE TITLE
serverリソースで共有ネットワーク利用時、 ipaddress に "" を指定しているとapply 後も差分が残る

### ISSUE THREAD

**Issue by hitsumabushi** [sacloud/terraform-provider-sakuracloud#240]
# 発生するバージョン
v1.0.0 

# 概要
nic = "shared" にしているサーバーに対して、 ipaddress に `""`を指定した場合、applyした後もplanでdiffが出る。
前のバージョンまでは動いていたのですが、 v1.0.0 ではdiffが出るようです。

## 再現コード
```
variable "password" {
  default = "hogehoge-!2"
}

variable "nic" {
  default = "shared"
}

variable "ipaddress" {
  default = "192.168.1.1"
}

provider sakuracloud {
  zone = "is1b"
}

# パブリックアーカイブ(OS)のID参照用のデータリソース定義
data sakuracloud_archive "centos" {
  os_type = "centos"
}

resource "sakuracloud_disk" "disk01" {
  name              = "disk01"
  source_archive_id = "${data.sakuracloud_archive.centos.id}"
  password          = "${var.password}"
  disable_pw_auth   = true
}

resource "sakuracloud_server" "server01" {
  name  = "server01"
  disks = ["${sakuracloud_disk.disk01.id}"]
  nic   = "${var.nic}"
  ipaddress = "${var.nic == "shared" ? "" : var.ipaddress}"
}
```

# 補足
なぜ、ipaddress に `""` を入れたいのか、ということを補足します。

serverやdisk、dns-record リソースをまとめて作成できるようにmoduleを定義しており、変数としてipaddressなどを指定しています。
その中でサーバーが利用しているNICが共有セグメントかどうかを判別し、スイッチの場合変数からIPを参照し、共有セグメントの場合には、(ipaddress として指定できるものがなく、terraform ではそれほど柔軟にif文を書けないため) `""` を指定していました。
```
  ipaddress = "${var.nic == "shared" ? "" : element(var.ipaddresses, count.index)}"
```

**Comment by yamamoto-febc** [comment]
ご報告ありがとうございます！

補足いただいたユースケースは十分に一般的なものだと思います。
このため、#213 , #234 と同じく差分検知部分の修正を行います。
(`v1.0.1`にて対応します)

**Comment by yamamoto-febc** [comment]
#243 にて対応しました。
この対応を含む`v1.0.1`を近々リリースしますのでしばしお待ちください:bow:

**Comment by yamamoto-febc** [comment]
#243 にて初回のapply時にサーバのIPアドレスを参照しているとエラーとなるようになりました。
このため一旦 #243 をrevertします。

plan後に差分が出る現象については再度対応方法を検討の上対応します。
